general.import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
opacity = 0.8
blur = true
padding = { x = 10, y = 10 }
dynamic_padding = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 16
